### ISSUE TITLE
How do you end/close a haredis connection?

### ISSUE THREAD

**Issue by nickminutello** [carlos8f/haredis#2]
The end() method on the underlying connection doesnt seem to be present on haredis. What are you meant to do instead to close down all connections & free resources?

**Comment by nickminutello** [comment]
I found I could call .quit()

But quit() doesnt actually quit if one of the connections are down? (it keeps trying to connect)

**Comment by carlos8f** [comment]
probably a bug, will put it on the "todo" list.

**Comment by nickminutello** [comment]
Cheers, thanks
