### ISSUE TITLE
Using haredis with multiple application instances

### ISSUE THREAD

**Issue by PaquitoSoft** [carlos8f/haredis#24]
Hello there,

This is a question rather than an issue, but I would kike to know if this module can be used when you have several instances of your application running on different machines.
In my case, my web application will be running in three different machines and I don't know how could the master election mechanism would work when there are several application clients running this module.

Thanks.

**Comment by carlos8f** [comment]
Hi,

Thanks for your interest. Haredis clients can be spread across any machines
that can connect to the redis servers. The clients communicate and
negotiate a master through the redis servers (pub/sub, etc), and do not
connect to other clients via some other IPC. Sorry this was not clear from
the readme.

Cheers,
Carlos

**Comment by PaquitoSoft** [comment]
Hi Carlos,

Thanks a lot for the explanation. I guess all the voting process when an instance of Redis falls down is part of the magic from your module.

I also would like to ask about usgin this module in an environment where sharding is needed. Is there any setup where I can use several masters where I'd use to write stuff.
I'm planning of using a consistent-sharding module for that requirement and your module to get high availability.

Thanks, again.

**Comment by carlos8f** [comment]
Haredis (or node_redis) has no method to let you inject a hashing algorithm
to talk to multiple masters. Sharding is a difficult problem obviously, is
out of the haredis scope, and only a subset of commands can be supported.
Redis Cluster has been in development for a while which should solve the
sharding problem in the most efficient way possible (at the c-compiled
server level). Until that becomes stable you'd have to build a code layer
on top of haredis to switch between multiple redis replica sets based on
your partitioning algorithm.

Cheers,
Carlos

**Comment by PaquitoSoft** [comment]
Thanks!
