### ISSUE TITLE
Periodically changing of master 

### ISSUE THREAD

**Issue by Rolandvl** [carlos8f/haredis#6]
Hi,
- Do i have trouble with my installation or is it a normal way that master change on regular basis ?
- Is there any problem having 2 redis cluster used by the same node client :
  client1 = createClient ([r1:p1, r2:p2, r3:p3 ])
  client2 =  createClient ([r4:p4, r5:p5, r6:p6 ])
- And last, what appends if I had 2 node clients with different configs:
  node1
   client = createClient ([r1:p1, r2:p2, r3:p3 ])
  node2
  client =createClient ([r1:p1, r2:p2, r3:p3 , r4:p4])

(typically, when I wanted to add new cluster, but don't want to stop previous server while the new one is not ready)

Thanks.

**Comment by carlos8f** [comment]
1. what do you see in the log? haredis will trigger failover if the master connection breaks, which can happen in various cases like a temporary network outage. In theory, this is nothing to worry about and your app will carry on as if nothing happened.
2. looks like there's no problem with that, haredis will find (or elect) a master in each group of nodes, and the clients will function independently.
3. this would only pose a problem if `r4:p4` is/becomes master. in that case, the first client doesn't know about the master node, and would attempt to elect a master within its known pool. then, if the first client elects a new master that isn't part of the second client's pool, you'd run into an infinite failover loop. So having clients with different configs might work for a short time (while you restart your servers) but it would be safer to shut down the old configs before bringing up the new ones. And for sure, don't run conflicting configurations for an extended period to avoid infinite failover loops.

Cheers,
Carlos
